#version 450
#extension GL_ARB_shading_language_include : require
#include "simulatingcommon.h"

layout(local_size_x = 256) in;
void main() 
{
    int index = int(gl_GlobalInvocationID.x);
    if (index >= GRID_RESOLUTION * GRID_RESOLUTION * GRID_RESOLUTION) {
        return;
    }

    Cell cell = grid[index];
    cell.vel  = vec3(0.0, 0.0, 0.0); 
    cell.mass = 0.0;          

    grid[index] = cell;
}