#version 450
#extension GL_ARB_shading_language_include : require

#include "simulationcommon.h"

layout(local_size_x=256,local_size_y=1,local_size_z=1) in;

void main()
{
    uint globalindex = gl_GlobalInvocationID.x;
    uint layer_num = push_constant.layer_num;
    uint true_index = (globalindex + 1) * layer_num - 1;
    if (true_index < gridCount)
    {
        neighborCount[true_index] += neighborCount[true_index - layer_num / 2];
    }
}