#version 450
#extension GL_ARB_shading_language_include : require

#include "simulationcommon_sph.h"

layout(local_size_x=256,local_size_y=1,local_size_z=1) in;


void main() {
    
    uint particleindex = gl_GlobalInvocationID.x;

    if (particleindex < numParticles){
		particlesOut[particleindex] = particlesIn[particleindex];
		particlesOut[particleindex].DeltaLocation = vec3(0.0);
        wcsphExternalForce[particleindex] = vec4(0.0);
    }
}